"""
MQL5 EA Code Generator

Generates MQL5 EA code from TRD documents.
"""
import logging
from datetime import datetime
from typing import Dict, Any, Optional, Tuple

from src.trd.schema import TRDDocument
from src.mql5.templates.ea_base_template import EA_TEMPLATE, TRD_TO_MQL5_MAPPING

logger = logging.getLogger(__name__)


class GenerationError(Exception):
    """Exception raised for MQL5 generation errors."""
    pass


class MQL5Generator:
    """
    Generates MQL5 EA code from TRD documents.

    Maps TRD parameters to MQL5 input variables and generates
    complete .mq5 file content.
    """

    def __init__(self):
        self._generated_code: Optional[str] = None

    def generate(self, trd: TRDDocument) -> str:
        """
        Generate MQL5 EA code from TRD document.

        Args:
            trd: Validated TRD document

        Returns:
            Generated MQL5 code as string

        Raises:
            GenerationError: If generation fails
        """
        if not trd.strategy_id or not trd.strategy_name:
            raise GenerationError("TRD must have strategy_id and strategy_name")

        # Prepare template variables
        variables = self._prepare_template_variables(trd)

        # Generate code from template
        code = EA_TEMPLATE

        # Replace all placeholders
        for key, value in variables.items():
            placeholder = "{{" + key + "}}"
            code = code.replace(placeholder, str(value))

        # Remove any remaining placeholders (set to defaults)
        import re
        code = re.sub(r'\{\{(\w+)\}\}', '', code)

        self._generated_code = code
        logger.info(f"Generated MQL5 code for {trd.strategy_id}")

        return code

    def _prepare_template_variables(self, trd: TRDDocument) -> Dict[str, Any]:
        """Prepare template variables from TRD document."""
        # Core variables
        variables = {
            "strategy_name": trd.strategy_name.replace(" ", "_"),
            "strategy_id": trd.strategy_id,
            "version": trd.version,
            "generated_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "strategy_type": trd.strategy_type.value if hasattr(trd.strategy_type, 'value') else str(trd.strategy_type) if trd.strategy_type else "trend",
            "strategy_description": trd.description or "Generated by QUANTMINDX",
        }

        # Symbol and timeframe
        variables["symbol"] = trd.symbol
        variables["timeframe"] = trd.timeframe

        # Map TRD parameters to MQL5 inputs
        self._map_parameters(trd, variables)

        # Position sizing defaults
        if trd.position_sizing:
            ps = trd.position_sizing
            variables["fixed_lot_size"] = str(ps.fixed_lot_size)
            variables["max_lots"] = str(ps.max_lots)
            variables["risk_percent"] = str(ps.risk_percent)
        else:
            variables["fixed_lot_size"] = "0.01"
            variables["max_lots"] = "1.0"
            variables["risk_percent"] = "1.0"

        # Set defaults for missing parameters
        defaults = {
            "magic_number": "123456",
            "max_orders": "5",
            "spread_filter": "30",
            "slippage": "3",
            "daily_loss_cap": "5.0",
            "session_mask": "UK/US",
            "force_close_hour": "22",
            "overnight_hold": "false",
            "use_trailing_stop": "false",
            "trailing_distance": "50",
            "use_break_even": "false",
            "break_even_trigger": "100",
            "break_even_distance": "10",
            "ma_fast": "10",
            "ma_slow": "20",
        }

        for key, default_value in defaults.items():
            if key not in variables:
                variables[key] = default_value

        return variables

    def _map_parameters(self, trd: TRDDocument, variables: Dict[str, Any]) -> None:
        """Map TRD parameters to template variables."""
        for trd_param, (mql_var, mql_type) in TRD_TO_MQL5_MAPPING.items():
            value = trd.parameters.get(trd_param)

            if value is not None:
                # Convert boolean to MQL5 format
                if mql_type == "bool":
                    value = "true" if value else "false"
                elif mql_type == "string":
                    value = str(value)

                variables[mql_var] = value

    def save_to_file(self, code: str, file_path: str) -> None:
        """
        Save generated code to file.

        Args:
            code: MQL5 code to save
            file_path: Full path to save file
        """
        import os

        # Ensure directory exists
        os.makedirs(os.path.dirname(file_path), exist_ok=True)

        with open(file_path, 'w') as f:
            f.write(code)

        logger.info(f"Saved MQL5 code to {file_path}")

    def get_generated_code(self) -> Optional[str]:
        """Get the last generated code."""
        return self._generated_code

    def validate_mql5_syntax(self, code: str) -> Tuple[bool, str]:
        """
        Basic MQL5 syntax validation.

        Note: This is a basic check only. Full validation requires
        the MQL5 compiler.

        Args:
            code: MQL5 code to validate

        Returns:
            Tuple of (is_valid, error_message)
        """
        # Check for common issues
        lines = code.split('\n')
        brace_count = 0
        paren_count = 0

        for i, line in enumerate(lines, 1):
            # Count braces
            brace_count += line.count('{') - line.count('}')
            paren_count += line.count('(') - line.count(')')

            # Check for common syntax errors
            if ';;' in line:
                return False, f"Line {i}: Double semicolon"

            if '==' in line and 'if(' not in line and 'while(' not in line and 'for(' not in line:
                # Potential assignment error
                if ' = ' not in line and '!=' not in line:
                    pass  # Could be a warning

        if brace_count != 0:
            return False, f"Unmatched braces: {brace_count} difference"

        if paren_count != 0:
            return False, f"Unmatched parentheses: {paren_count} difference"

        # Check for required functions
        required_functions = ['OnInit', 'OnTick', 'OnDeinit']
        for func in required_functions:
            if func not in code:
                return False, f"Missing required function: {func}"

        return True, ""
