"""
TRD Validation Schema for Analyst Agent.

This module defines the Pydantic models for validating Trading Requirements Documents (TRDs)
generated by the Analyst agent.
"""

import re
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, field_validator, model_validator
from enum import Enum


class TimeFrame(str, Enum):
    """Supported trading timeframes."""
    M1 = "M1"
    M5 = "M5"
    M15 = "M15"
    M30 = "M30"
    H1 = "H1"
    H4 = "H4"
    D1 = "D1"
    W1 = "W1"
    MN = "MN"


class OrderType(str, Enum):
    """Order types for entries and exits."""
    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"


class PositionSide(str, Enum):
    """Position sides."""
    LONG = "long"
    SHORT = "short"
    BOTH = "both"


class RiskManagement(BaseModel):
    """Risk management configuration."""
    max_risk_per_trade: float = Field(
        default=0.02,
        ge=0.001,
        le=0.10,
        description="Maximum risk per trade as decimal (e.g., 0.02 = 2%)"
    )
    max_daily_drawdown: float = Field(
        default=0.05,
        ge=0.01,
        le=0.20,
        description="Maximum daily drawdown as decimal"
    )
    max_open_positions: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Maximum number of concurrent open positions"
    )
    use_kelly_criterion: bool = Field(
        default=False,
        description="Whether to use Kelly criterion for position sizing"
    )
    kelly_fraction: Optional[float] = Field(
        default=None,
        ge=0.1,
        le=1.0,
        description="Kelly fraction if using Kelly criterion (e.g., 0.5 = half Kelly)"
    )
    
    @model_validator(mode='after')
    def validate_kelly(self):
        """Validate Kelly criterion configuration."""
        if self.use_kelly_criterion and self.kelly_fraction is None:
            self.kelly_fraction = 0.5  # Default to half Kelly
        return self


class EntryRule(BaseModel):
    """Entry rule configuration."""
    name: str = Field(..., min_length=1, description="Name of the entry rule")
    description: str = Field(..., min_length=10, description="Detailed description of the entry rule")
    conditions: List[str] = Field(
        default_factory=list,
        min_length=1,
        description="List of conditions that must be met for entry"
    )
    order_type: OrderType = Field(
        default=OrderType.MARKET,
        description="Type of order to use for entry"
    )
    time_filter: Optional[str] = Field(
        default=None,
        description="Time filter for entry (e.g., '09:00-17:00')"
    )
    
    @field_validator('conditions')
    @classmethod
    def validate_conditions(cls, v):
        """Ensure at least one condition is specified."""
        if not v:
            raise ValueError("At least one entry condition must be specified")
        return v


class ExitRule(BaseModel):
    """Exit rule configuration."""
    name: str = Field(..., min_length=1, description="Name of the exit rule")
    description: str = Field(..., min_length=10, description="Detailed description of the exit rule")
    conditions: List[str] = Field(
        default_factory=list,
        min_length=1,
        description="List of conditions that trigger exit"
    )
    order_type: OrderType = Field(
        default=OrderType.MARKET,
        description="Type of order to use for exit"
    )
    
    @field_validator('conditions')
    @classmethod
    def validate_conditions(cls, v):
        """Ensure at least one condition is specified."""
        if not v:
            raise ValueError("At least one exit condition must be specified")
        return v


class StopLossConfig(BaseModel):
    """Stop loss configuration."""
    type: str = Field(
        ...,
        description="Type of stop loss: 'fixed', 'trailing', 'atr', 'swing_low_high'"
    )
    value: float = Field(
        ...,
        gt=0,
        description="Stop loss value (pips for fixed, multiplier for ATR)"
    )
    trailing_step: Optional[float] = Field(
        default=None,
        ge=0,
        description="Trailing step in pips (for trailing stop)"
    )
    
    @model_validator(mode='after')
    def validate_trailing(self):
        """Validate trailing stop configuration."""
        if self.type == 'trailing' and self.trailing_step is None:
            self.trailing_step = self.value  # Default trailing step to stop distance
        return self


class TakeProfitConfig(BaseModel):
    """Take profit configuration."""
    type: str = Field(
        ...,
        description="Type of take profit: 'fixed', 'risk_reward', 'fibonacci'"
    )
    value: float = Field(
        ...,
        gt=0,
        description="Take profit value (pips for fixed, ratio for risk_reward)"
    )
    partial_exits: Optional[List[Dict[str, float]]] = Field(
        default=None,
        description="Partial exit configuration: [{'level': 1.0, 'close_percent': 50}]"
    )


class IndicatorConfig(BaseModel):
    """Indicator configuration."""
    name: str = Field(..., description="Name of the indicator")
    parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Indicator parameters"
    )
    timeframe: Optional[TimeFrame] = Field(
        default=None,
        description="Indicator timeframe (if different from main)"
    )


class KellyIntegration(BaseModel):
    """Kelly criterion integration configuration."""
    enabled: bool = Field(default=False, description="Whether Kelly criterion is enabled")
    lookback_period: int = Field(
        default=100,
        ge=20,
        le=500,
        description="Number of trades to calculate Kelly from"
    )
    max_position_size: float = Field(
        default=0.10,
        ge=0.01,
        le=0.25,
        description="Maximum position size as fraction of account"
    )
    min_win_rate: float = Field(
        default=0.40,
        ge=0.30,
        le=0.70,
        description="Minimum win rate to use Kelly"
    )
    safety_fraction: float = Field(
        default=0.5,
        ge=0.25,
        le=1.0,
        description="Fraction of Kelly to use (e.g., 0.5 = half Kelly)"
    )


class TRDSchema(BaseModel):
    """
    Trading Requirements Document Schema.
    
    This schema validates the structure and content of TRDs generated
    by the Analyst agent.
    """
    # Required fields
    strategy_name: str = Field(
        ...,
        min_length=3,
        max_length=100,
        description="Name of the trading strategy"
    )
    description: str = Field(
        ...,
        min_length=50,
        description="Detailed description of the strategy"
    )
    
    # Entry and exit rules
    entry_rules: List[EntryRule] = Field(
        ...,
        min_length=1,
        description="List of entry rules"
    )
    exit_rules: List[ExitRule] = Field(
        ...,
        min_length=1,
        description="List of exit rules"
    )
    
    # Stop loss and take profit
    stop_loss: StopLossConfig = Field(
        ...,
        description="Stop loss configuration"
    )
    take_profit: TakeProfitConfig = Field(
        ...,
        description="Take profit configuration"
    )
    
    # Risk management
    risk_management: RiskManagement = Field(
        default_factory=RiskManagement,
        description="Risk management configuration"
    )
    
    # Kelly integration
    kelly_integration: KellyIntegration = Field(
        default_factory=KellyIntegration,
        description="Kelly criterion integration configuration"
    )
    
    # Trading parameters
    timeframe: TimeFrame = Field(
        ...,
        description="Primary trading timeframe"
    )
    symbols: List[str] = Field(
        ...,
        min_length=1,
        description="List of trading symbols (e.g., ['EURUSD', 'GBPUSD'])"
    )
    position_side: PositionSide = Field(
        default=PositionSide.BOTH,
        description="Position side(s) to trade"
    )
    
    # Indicators
    indicators: List[IndicatorConfig] = Field(
        default_factory=list,
        description="List of indicators used by the strategy"
    )
    
    # Additional configuration
    additional_filters: Optional[List[str]] = Field(
        default=None,
        description="Additional filters (e.g., news filter, session filter)"
    )
    max_spread: Optional[float] = Field(
        default=None,
        ge=0,
        description="Maximum allowed spread in pips"
    )
    
    # Metadata
    version: str = Field(default="1.0.0", description="TRD version")
    author: Optional[str] = Field(default=None, description="Strategy author")
    created_at: Optional[str] = Field(default=None, description="Creation timestamp")
    tags: Optional[List[str]] = Field(default=None, description="Strategy tags")
    
    @field_validator('strategy_name')
    @classmethod
    def validate_strategy_name(cls, v):
        """Validate strategy name format."""
        # Allow alphanumeric, spaces, underscores, and hyphens
        if not re.match(r'^[a-zA-Z0-9_\s\-]+$', v):
            raise ValueError(
                "Strategy name can only contain letters, numbers, spaces, underscores, and hyphens"
            )
        return v
    
    @field_validator('symbols')
    @classmethod
    def validate_symbols(cls, v):
        """Validate trading symbols."""
        if not v:
            raise ValueError("At least one trading symbol must be specified")
        
        # Validate symbol format (basic check)
        for symbol in v:
            if not re.match(r'^[A-Z]{3,6}(?:[A-Z]{3,6})?$', symbol):
                raise ValueError(f"Invalid symbol format: {symbol}")
        
        return v
    
    @model_validator(mode='after')
    def validate_entry_exit_consistency(self):
        """Validate consistency between entry and exit rules."""
        # Ensure at least one entry and one exit rule
        if not self.entry_rules:
            raise ValueError("At least one entry rule is required")
        if not self.exit_rules:
            raise ValueError("At least one exit rule is required")
        
        return self


class TRDValidationResult(BaseModel):
    """Result of TRD validation."""
    valid: bool = Field(..., description="Whether the TRD is valid")
    errors: List[str] = Field(default_factory=list, description="Validation errors")
    warnings: List[str] = Field(default_factory=list, description="Validation warnings")
    trd: Optional[TRDSchema] = Field(default=None, description="Validated TRD object")
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "valid": self.valid,
            "errors": self.errors,
            "warnings": self.warnings,
            "trd": self.trd.model_dump() if self.trd else None
        }


def validate_trd(trd_content: str) -> TRDValidationResult:
    """
    Validate a TRD markdown content.
    
    This function parses TRD markdown content and validates it against
    the TRDSchema.
    
    Args:
        trd_content: TRD content as markdown string
        
    Returns:
        TRDValidationResult with validation status and any errors/warnings
    """
    import json
    
    errors = []
    warnings = []
    
    # Try to extract JSON from markdown
    json_match = re.search(r'```json\s*(.*?)\s*```', trd_content, re.DOTALL)
    
    if json_match:
        try:
            trd_data = json.loads(json_match.group(1))
        except json.JSONDecodeError as e:
            errors.append(f"Invalid JSON in TRD: {e}")
            return TRDValidationResult(valid=False, errors=errors)
    else:
        # Try to parse as pure JSON
        try:
            trd_data = json.loads(trd_content)
        except json.JSONDecodeError:
            # Try to parse from markdown structure
            trd_data = parse_trd_from_markdown(trd_content)
    
    # Validate against schema
    try:
        trd = TRDSchema(**trd_data)
        
        # Add warnings for optional fields
        if not trd.indicators:
            warnings.append("No indicators specified")
        if not trd.additional_filters:
            warnings.append("No additional filters specified")
        if trd.max_spread is None:
            warnings.append("No maximum spread specified")
        
        return TRDValidationResult(
            valid=True,
            warnings=warnings,
            trd=trd
        )
        
    except Exception as e:
        errors.append(f"Schema validation error: {e}")
        return TRDValidationResult(valid=False, errors=errors)


def parse_trd_from_markdown(markdown_content: str) -> Dict[str, Any]:
    """
    Parse TRD from markdown structure.
    
    This is a fallback parser for TRDs that are formatted as markdown
    without embedded JSON.
    
    Args:
        markdown_content: TRD content as markdown string
        
    Returns:
        Dictionary with parsed TRD data
    """
    data = {}
    
    # Extract strategy name
    name_match = re.search(r'^#\s+(.+)$', markdown_content, re.MULTILINE)
    if name_match:
        data['strategy_name'] = name_match.group(1).strip()
    
    # Extract description
    desc_match = re.search(r'##\s+Description\s*\n+(.+?)(?=\n##|\Z)', markdown_content, re.DOTALL)
    if desc_match:
        data['description'] = desc_match.group(1).strip()
    
    # Extract timeframe
    tf_match = re.search(r'\*\*Timeframe:\*\*\s*(\w+)', markdown_content)
    if tf_match:
        data['timeframe'] = tf_match.group(1)
    
    # Extract symbols
    symbols_match = re.search(r'\*\*Symbols:\*\*\s*(.+)', markdown_content)
    if symbols_match:
        symbols_str = symbols_match.group(1)
        data['symbols'] = [s.strip() for s in symbols_str.split(',')]
    
    # Set defaults for required fields
    if 'strategy_name' not in data:
        data['strategy_name'] = "Unnamed Strategy"
    if 'description' not in data:
        data['description'] = "No description provided"
    if 'timeframe' not in data:
        data['timeframe'] = "H1"
    if 'symbols' not in data:
        data['symbols'] = ["EURUSD"]
    
    # Add default entry/exit rules
    data['entry_rules'] = [{
        'name': 'Default Entry',
        'description': 'Default entry rule - requires specification',
        'conditions': ['Condition to be specified']
    }]
    data['exit_rules'] = [{
        'name': 'Default Exit',
        'description': 'Default exit rule - requires specification',
        'conditions': ['Condition to be specified']
    }]
    
    # Add default stop loss and take profit
    data['stop_loss'] = {
        'type': 'fixed',
        'value': 50
    }
    data['take_profit'] = {
        'type': 'risk_reward',
        'value': 2.0
    }
    
    return data


def create_trd_template() -> str:
    """
    Create a TRD template with all required fields.
    
    Returns:
        TRD template as markdown string
    """
    template = """# Strategy Name

## Description
Detailed description of the trading strategy, including its purpose, market conditions it's designed for, and expected behavior.

## Configuration

```json
{
  "strategy_name": "Your Strategy Name",
  "description": "Detailed strategy description (minimum 50 characters)",
  "entry_rules": [
    {
      "name": "Primary Entry",
      "description": "Description of the primary entry condition",
      "conditions": [
        "Price crosses above 20 EMA",
        "RSI is below 70",
        "MACD histogram is positive"
      ],
      "order_type": "market"
    }
  ],
  "exit_rules": [
    {
      "name": "Take Profit Exit",
      "description": "Exit when take profit is reached",
      "conditions": ["Take profit level reached"],
      "order_type": "limit"
    },
    {
      "name": "Stop Loss Exit",
      "description": "Exit when stop loss is triggered",
      "conditions": ["Stop loss level reached"],
      "order_type": "stop"
    }
  ],
  "stop_loss": {
    "type": "fixed",
    "value": 50
  },
  "take_profit": {
    "type": "risk_reward",
    "value": 2.0
  },
  "risk_management": {
    "max_risk_per_trade": 0.02,
    "max_daily_drawdown": 0.05,
    "max_open_positions": 3,
    "use_kelly_criterion": false
  },
  "kelly_integration": {
    "enabled": false,
    "lookback_period": 100,
    "max_position_size": 0.10,
    "min_win_rate": 0.40,
    "safety_fraction": 0.5
  },
  "timeframe": "H1",
  "symbols": ["EURUSD", "GBPUSD"],
  "position_side": "both",
  "indicators": [
    {
      "name": "EMA",
      "parameters": {"period": 20}
    },
    {
      "name": "RSI",
      "parameters": {"period": 14}
    }
  ],
  "additional_filters": ["news_filter", "session_filter"],
  "max_spread": 2.0
}
```

## Notes
- Additional notes about the strategy
- Known limitations
- Recommended account types
"""
    return template
