"""
Code Quality Checker for MQL5 Code.

This module provides code quality analysis for MQL5 code generated by the QuantCode agent,
checking for naming conventions, complexity, documentation, and structure.
"""

import re
import logging
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field
from enum import Enum

logger = logging.getLogger(__name__)


class IssueSeverity(str, Enum):
    """Severity levels for code quality issues."""
    CRITICAL = "critical"
    ERROR = "error"
    WARNING = "warning"
    INFO = "info"
    STYLE = "style"


class IssueCategory(str, Enum):
    """Categories for code quality issues."""
    NAMING = "naming"
    COMPLEXITY = "complexity"
    DOCUMENTATION = "documentation"
    STRUCTURE = "structure"
    PERFORMANCE = "performance"
    SECURITY = "security"
    BEST_PRACTICE = "best_practice"


@dataclass
class CodeIssue:
    """A single code quality issue."""
    line: int
    column: int
    severity: IssueSeverity
    category: IssueCategory
    message: str
    suggestion: Optional[str] = None
    rule_id: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "line": self.line,
            "column": self.column,
            "severity": self.severity.value,
            "category": self.category.value,
            "message": self.message,
            "suggestion": self.suggestion,
            "rule_id": self.rule_id
        }


@dataclass
class CodeQualityResult:
    """Result of code quality check."""
    score: float  # 0-100
    issues: List[CodeIssue]
    metrics: Dict[str, Any]
    passed: bool
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "score": self.score,
            "issues": [issue.to_dict() for issue in self.issues],
            "metrics": self.metrics,
            "passed": self.passed,
            "issue_counts": {
                "critical": sum(1 for i in self.issues if i.severity == IssueSeverity.CRITICAL),
                "error": sum(1 for i in self.issues if i.severity == IssueSeverity.ERROR),
                "warning": sum(1 for i in self.issues if i.severity == IssueSeverity.WARNING),
                "info": sum(1 for i in self.issues if i.severity == IssueSeverity.INFO),
                "style": sum(1 for i in self.issues if i.severity == IssueSeverity.STYLE)
            }
        }


class MQL5CodeQualityChecker:
    """
    Code quality checker for MQL5 code.
    
    Checks for:
    - Naming conventions (PascalCase for classes, camelCase for functions)
    - Cyclomatic complexity
    - Documentation completeness
    - Code structure and organization
    - Performance patterns
    - Security best practices
    """
    
    # Naming convention patterns
    CLASS_PATTERN = re.compile(r'^[A-Z][a-zA-Z0-9]*$')
    FUNCTION_PATTERN = re.compile(r'^[a-z][a-zA-Z0-9]*$')
    VARIABLE_PATTERN = re.compile(r'^[a-z][a-zA-Z0-9_]*$')
    CONSTANT_PATTERN = re.compile(r'^[A-Z][A-Z0-9_]*$')
    
    # MQL5 specific patterns
    INPUT_PARAM_PATTERN = re.compile(r'input\s+(\w+)\s+(\w+)\s*;')
    PROPERTY_PATTERN = re.compile(r'#property\s+(\w+)\s+(.+)')
    INCLUDE_PATTERN = re.compile(r'#include\s*[<"](.+)[>"]')
    FUNCTION_DEF_PATTERN = re.compile(
        r'(\w+)\s+(\w+)\s*\(([^)]*)\)\s*\{',
        re.MULTILINE
    )
    CLASS_DEF_PATTERN = re.compile(
        r'class\s+(\w+)(?:\s*:\s*(?:public|protected|private)\s+(\w+))?\s*\{',
        re.MULTILINE
    )
    
    def __init__(
        self,
        max_complexity: int = 15,
        min_documentation_ratio: float = 0.3,
        max_function_length: int = 100,
        max_file_length: int = 1000
    ):
        """
        Initialize code quality checker.
        
        Args:
            max_complexity: Maximum cyclomatic complexity per function
            min_documentation_ratio: Minimum ratio of comments to code
            max_function_length: Maximum lines per function
            max_file_length: Maximum lines per file
        """
        self.max_complexity = max_complexity
        self.min_documentation_ratio = min_documentation_ratio
        self.max_function_length = max_function_length
        self.max_file_length = max_file_length
    
    def check_code_quality(self, code: str) -> CodeQualityResult:
        """
        Check code quality of MQL5 code.
        
        Args:
            code: MQL5 source code
            
        Returns:
            CodeQualityResult with score, issues, and metrics
        """
        issues: List[CodeIssue] = []
        lines = code.split('\n')
        
        # Run all checks
        issues.extend(self._check_naming_conventions(code, lines))
        issues.extend(self._check_complexity(code, lines))
        issues.extend(self._check_documentation(code, lines))
        issues.extend(self._check_structure(code, lines))
        issues.extend(self._check_performance(code, lines))
        issues.extend(self._check_best_practices(code, lines))
        
        # Calculate metrics
        metrics = self._calculate_metrics(code, lines)
        
        # Calculate score
        score = self._calculate_score(issues, metrics)
        
        # Determine if passed
        critical_errors = sum(1 for i in issues if i.severity == IssueSeverity.CRITICAL)
        errors = sum(1 for i in issues if i.severity == IssueSeverity.ERROR)
        passed = critical_errors == 0 and errors == 0 and score >= 60
        
        return CodeQualityResult(
            score=score,
            issues=issues,
            metrics=metrics,
            passed=passed
        )
    
    def _check_naming_conventions(self, code: str, lines: List[str]) -> List[CodeIssue]:
        """Check naming conventions."""
        issues = []
        
        # Check class names
        for match in self.CLASS_DEF_PATTERN.finditer(code):
            class_name = match.group(1)
            if not self.CLASS_PATTERN.match(class_name):
                line_num = code[:match.start()].count('\n') + 1
                issues.append(CodeIssue(
                    line=line_num,
                    column=match.start() - code.rfind('\n', 0, match.start()),
                    severity=IssueSeverity.WARNING,
                    category=IssueCategory.NAMING,
                    message=f"Class name '{class_name}' should use PascalCase",
                    suggestion=f"Consider renaming to '{self._to_pascal_case(class_name)}'",
                    rule_id="NAMING001"
                ))
        
        # Check function names
        for match in self.FUNCTION_DEF_PATTERN.finditer(code):
            func_name = match.group(2)
            # Skip MQL5 built-in functions
            if func_name in ['OnInit', 'OnDeinit', 'OnTick', 'OnCalculate', 'OnTimer', 'OnTester', 'OnChartEvent', 'OnTrade', 'OnTradeTransaction']:
                continue
            
            if not self.FUNCTION_PATTERN.match(func_name):
                line_num = code[:match.start()].count('\n') + 1
                issues.append(CodeIssue(
                    line=line_num,
                    column=match.start() - code.rfind('\n', 0, match.start()),
                    severity=IssueSeverity.WARNING,
                    category=IssueCategory.NAMING,
                    message=f"Function name '{func_name}' should use camelCase",
                    suggestion=f"Consider renaming to '{self._to_camel_case(func_name)}'",
                    rule_id="NAMING002"
                ))
        
        return issues
    
    def _check_complexity(self, code: str, lines: List[str]) -> List[CodeIssue]:
        """Check cyclomatic complexity."""
        issues = []
        
        # Count decision points
        decision_patterns = [
            (r'\bif\s*\(', 'if statement'),
            (r'\belse\s+if\s*\(', 'else if statement'),
            (r'\bfor\s*\(', 'for loop'),
            (r'\bwhile\s*\(', 'while loop'),
            (r'\bswitch\s*\(', 'switch statement'),
            (r'\bcase\s+', 'case label'),
            (r'\?\s*:', 'ternary operator'),
            (r'\|\|', 'logical OR'),
            (r'\&\&', 'logical AND'),
        ]
        
        # Find function boundaries
        function_starts = []
        for match in self.FUNCTION_DEF_PATTERN.finditer(code):
            line_num = code[:match.start()].count('\n') + 1
            function_starts.append((match.start(), match.end(), match.group(2), line_num))
        
        # Calculate complexity for each function
        for start, end, func_name, line_num in function_starts:
            func_code = code[start:end + code[end:].find('}') + 1] if '}' in code[end:] else code[start:]
            
            complexity = 1  # Base complexity
            for pattern, _ in decision_patterns:
                complexity += len(re.findall(pattern, func_code))
            
            if complexity > self.max_complexity:
                issues.append(CodeIssue(
                    line=line_num,
                    column=1,
                    severity=IssueSeverity.WARNING,
                    category=IssueCategory.COMPLEXITY,
                    message=f"Function '{func_name}' has complexity {complexity} (max: {self.max_complexity})",
                    suggestion="Consider breaking down into smaller functions",
                    rule_id="COMPLEX001"
                ))
        
        return issues
    
    def _check_documentation(self, code: str, lines: List[str]) -> List[CodeIssue]:
        """Check documentation completeness."""
        issues = []
        
        # Count comment lines
        comment_lines = 0
        for line in lines:
            stripped = line.strip()
            if stripped.startswith('//') or stripped.startswith('/*') or stripped.startswith('*'):
                comment_lines += 1
        
        # Calculate documentation ratio
        total_lines = len([l for l in lines if l.strip()])
        doc_ratio = comment_lines / total_lines if total_lines > 0 else 0
        
        if doc_ratio < self.min_documentation_ratio:
            issues.append(CodeIssue(
                line=1,
                column=1,
                severity=IssueSeverity.INFO,
                category=IssueCategory.DOCUMENTATION,
                message=f"Documentation ratio is {doc_ratio:.1%} (min: {self.min_documentation_ratio:.1%})",
                suggestion="Add more comments to explain complex logic",
                rule_id="DOC001"
            ))
        
        # Check for function documentation
        for match in self.FUNCTION_DEF_PATTERN.finditer(code):
            func_name = match.group(2)
            line_num = code[:match.start()].count('\n') + 1
            
            # Check if there's a comment before the function
            prev_line = lines[line_num - 2].strip() if line_num > 1 else ""
            if not prev_line.startswith('//') and not prev_line.startswith('/*'):
                issues.append(CodeIssue(
                    line=line_num,
                    column=1,
                    severity=IssueSeverity.STYLE,
                    category=IssueCategory.DOCUMENTATION,
                    message=f"Function '{func_name}' lacks documentation",
                    suggestion="Add a comment describing the function's purpose",
                    rule_id="DOC002"
                ))
        
        return issues
    
    def _check_structure(self, code: str, lines: List[str]) -> List[CodeIssue]:
        """Check code structure and organization."""
        issues = []
        
        # Check file length
        if len(lines) > self.max_file_length:
            issues.append(CodeIssue(
                line=1,
                column=1,
                severity=IssueSeverity.WARNING,
                category=IssueCategory.STRUCTURE,
                message=f"File has {len(lines)} lines (max: {self.max_file_length})",
                suggestion="Consider splitting into multiple files",
                rule_id="STRUCT001"
            ))
        
        # Check for required properties
        required_properties = ['copyright', 'version', 'description']
        found_properties = set()
        for match in self.PROPERTY_PATTERN.finditer(code):
            prop_name = match.group(1).lower()
            found_properties.add(prop_name)
        
        for prop in required_properties:
            if prop not in found_properties:
                issues.append(CodeIssue(
                    line=1,
                    column=1,
                    severity=IssueSeverity.INFO,
                    category=IssueCategory.STRUCTURE,
                    message=f"Missing #property {prop}",
                    suggestion=f"Add: #property {prop} \"value\"",
                    rule_id="STRUCT002"
                ))
        
        # Check for magic number
        if 'MagicNumber' not in code and 'MAGIC' not in code.upper():
            issues.append(CodeIssue(
                line=1,
                column=1,
                severity=IssueSeverity.WARNING,
                category=IssueCategory.STRUCTURE,
                message="No magic number defined for the EA",
                suggestion="Add a magic number to identify orders from this EA",
                rule_id="STRUCT003"
            ))
        
        return issues
    
    def _check_performance(self, code: str, lines: List[str]) -> List[CodeIssue]:
        """Check for performance issues."""
        issues = []
        
        # Check for repeated calculations in loops
        loop_patterns = [r'\bfor\s*\(', r'\bwhile\s*\(']
        for pattern in loop_patterns:
            for match in re.finditer(pattern, code):
                line_num = code[:match.start()].count('\n') + 1
                
                # Check for iHigh, iLow, iClose in loops without caching
                loop_end = code.find('}', match.start())
                if loop_end == -1:
                    loop_end = len(code)
                loop_code = code[match.start():loop_end]
                
                if loop_code.count('iHigh') > 3 or loop_code.count('iLow') > 3 or loop_code.count('iClose') > 3:
                    issues.append(CodeIssue(
                        line=line_num,
                        column=1,
                        severity=IssueSeverity.WARNING,
                        category=IssueCategory.PERFORMANCE,
                        message="Repeated price data calls in loop",
                        suggestion="Cache price data outside the loop",
                        rule_id="PERF001"
                    ))
                    break  # Only report once per loop
        
        # Check for OrdersTotal() in loops
        if re.search(r'OrdersTotal\s*\(\s*\)', code):
            for match in re.finditer(r'for\s*\([^)]*OrdersTotal', code):
                line_num = code[:match.start()].count('\n') + 1
                issues.append(CodeIssue(
                    line=line_num,
                    column=1,
                    severity=IssueSeverity.WARNING,
                    category=IssueCategory.PERFORMANCE,
                    message="OrdersTotal() called in loop condition",
                    suggestion="Cache OrdersTotal() result before the loop",
                    rule_id="PERF002"
                ))
        
        return issues
    
    def _check_best_practices(self, code: str, lines: List[str]) -> List[CodeIssue]:
        """Check for MQL5 best practices."""
        issues = []
        
        # Check for proper error handling
        if 'OrderSend' in code and 'GetLastError' not in code:
            issues.append(CodeIssue(
                line=1,
                column=1,
                severity=IssueSeverity.WARNING,
                category=IssueCategory.BEST_PRACTICE,
                message="OrderSend used without error checking",
                suggestion="Check return value and use GetLastError() for error handling",
                rule_id="BEST001"
            ))
        
        # Check for hardcoded lot sizes
        if re.search(r'OrderSend[^)]*\d+\.?\d*\s*,\s*OP_', code):
            issues.append(CodeIssue(
                line=1,
                column=1,
                severity=IssueSeverity.INFO,
                category=IssueCategory.BEST_PRACTICE,
                message="Hardcoded lot size detected",
                suggestion="Use dynamic position sizing based on risk",
                rule_id="BEST002"
            ))
        
        # Check for proper use of input parameters
        input_params = self.INPUT_PARAM_PATTERN.findall(code)
        if not input_params:
            issues.append(CodeIssue(
                line=1,
                column=1,
                severity=IssueSeverity.INFO,
                category=IssueCategory.BEST_PRACTICE,
                message="No input parameters defined",
                suggestion="Add input parameters for configurable values",
                rule_id="BEST003"
            ))
        
        return issues
    
    def _calculate_metrics(self, code: str, lines: List[str]) -> Dict[str, Any]:
        """Calculate code metrics."""
        # Count various elements
        total_lines = len(lines)
        code_lines = len([l for l in lines if l.strip() and not l.strip().startswith(('/', '*'))])
        comment_lines = len([l for l in lines if l.strip().startswith(('/', '*'))])
        blank_lines = total_lines - code_lines - comment_lines
        
        # Count functions and classes
        functions = len(self.FUNCTION_DEF_PATTERN.findall(code))
        classes = len(self.CLASS_DEF_PATTERN.findall(code))
        
        # Count includes
        includes = len(self.INCLUDE_PATTERN.findall(code))
        
        return {
            "total_lines": total_lines,
            "code_lines": code_lines,
            "comment_lines": comment_lines,
            "blank_lines": blank_lines,
            "functions": functions,
            "classes": classes,
            "includes": includes,
            "comment_ratio": comment_lines / code_lines if code_lines > 0 else 0
        }
    
    def _calculate_score(self, issues: List[CodeIssue], metrics: Dict[str, Any]) -> float:
        """Calculate overall quality score."""
        base_score = 100.0
        
        # Deduct points for issues
        for issue in issues:
            if issue.severity == IssueSeverity.CRITICAL:
                base_score -= 20
            elif issue.severity == IssueSeverity.ERROR:
                base_score -= 10
            elif issue.severity == IssueSeverity.WARNING:
                base_score -= 5
            elif issue.severity == IssueSeverity.INFO:
                base_score -= 2
            elif issue.severity == IssueSeverity.STYLE:
                base_score -= 1
        
        # Bonus for good documentation
        if metrics["comment_ratio"] > 0.3:
            base_score += 5
        
        # Bonus for reasonable file size
        if metrics["total_lines"] < 500:
            base_score += 5
        
        return max(0, min(100, base_score))
    
    def _to_pascal_case(self, name: str) -> str:
        """Convert name to PascalCase."""
        parts = re.split(r'[_\s]+', name)
        return ''.join(p.capitalize() for p in parts)
    
    def _to_camel_case(self, name: str) -> str:
        """Convert name to camelCase."""
        pascal = self._to_pascal_case(name)
        return pascal[0].lower() + pascal[1:] if pascal else ""


def check_code_quality(code: str) -> Dict[str, Any]:
    """
    Check code quality of MQL5 code.
    
    This is the main entry point for code quality checking.
    
    Args:
        code: MQL5 source code
        
    Returns:
        Dictionary containing quality check results
    """
    checker = MQL5CodeQualityChecker()
    result = checker.check_code_quality(code)
    return result.to_dict()
