"""
MQL5 EA Base Template

Template for generating MQL5 Expert Advisor code from TRD documents.
"""
import re
from datetime import datetime
from typing import Dict, Any, List, Tuple

EA_TEMPLATE = '''//+------------------------------------------------------------------+
//| {{strategy_name}}.mq5
//| Generated by QUANTMINDX Development Department
//| Strategy ID: {{strategy_id}}
//| Version: {{version}}
//| Generated: {{generated_date}}
//+------------------------------------------------------------------+
#property copyright "QUANTMINDX"
// @version=5
#property strict

//+------------------------------------------------------------------+
//| Includes
//+------------------------------------------------------------------+
#include <Trade/Trade.mqh>
#include <Trade/SymbolInfo.mqh>
#include <Trade/AccountInfo.mqh>

//+------------------------------------------------------------------+
//| Input Parameters
//+------------------------------------------------------------------+
input group "=== EA Configuration ==="
input string   InpExpertName = "{{strategy_name}}";  // EA Name
input int      InpMagicNumber = {{magic_number}};     // Magic Number
input int      InpMaxOrders = {{max_orders}};        // Max Orders

input group "=== Trading Parameters ==="
input double   InpMaxSpread = {{spread_filter}};      // Max Spread (points)
input int      InpSlippage = {{slippage}};           // Slippage (points)
input double   InpDailyLossCap = {{daily_loss_cap}};  // Daily Loss Cap (%)

input group "=== Session Settings ==="
input string   InpSessionMask = "{{session_mask}}";   // Session Mask (UK/US/Asia)
input int      InpForceCloseHour = {{force_close_hour}};  // Force Close Hour (0-23)
input bool     InpOvernightHold = {{overnight_hold}}; // Hold Overnight

input group "=== Position Management ==="
input double   InpFixedLot = {{fixed_lot_size}};      // Fixed Lot Size
input double   InpMaxLot = {{max_lots}};             // Max Lot Size
input double   InpRiskPercent = {{risk_percent}};     // Risk Percent
input bool     InpUseTrail = {{use_trailing_stop}};  // Use Trailing Stop
input int      InpTrailDistance = {{trailing_distance}}; // Trail Distance (points)
input bool     InpUseBreakEven = {{use_break_even}}; // Use Break Even
input int      InpBreakEvenTrigger = {{break_even_trigger}}; // Break Even Trigger (points)
input int      InpBreakEvenDist = {{break_even_distance}}; // Break Even Distance (points)

input group "=== ATR Stop Loss ==="
input bool     InpUseATRStop = false;              // Use ATR-based Stop Loss
input int      InpATRPeriod = 14;                   // ATR Period
input double   InpATRMultiplier = 1.5;               // ATR Multiplier (1.5x = 1.5R SL)

input group "=== Bot Configuration ==="
input string   InpBotType = "{{bot_type}}";        // Bot Type (scalping/orb/structural/swing)
input string   InpSessionTags = "{{session_tags}}"; // Session Tags (comma-separated: LONDONS,ASIA,NEWYORK)

input group "=== News Blackout ==="
input bool     InpUseNewsBlackout = {{news_blackout}};  // Enable News Blackout
input int      InpBlackoutMinutes = 15;              // Blackout Window (minutes before/after event)

input group "=== Hybrid SL/TP (Option B+C) ==="
input bool     InpUseHybridSLTP = true;               // Use Hybrid SL/TP Management
input double   InpBETriggerPct = 0.5;                // Breakeven Trigger (% of SL distance)
input double   InpPartialClosePct = 30;               // Partial Close % (at 1xSL profit)
input double   InpRVOLThreshold = 1.4;                 // RVOL threshold for 3R TP
input int      InpMaxHoldMinutes = 20;                // Max Hold Time (minutes)

//+------------------------------------------------------------------+
//| Global Variables
//+------------------------------------------------------------------+
CTrade          m_trade;
CSymbolInfo     m_symbol;
CAccountInfo    m_account;
datetime        g_last_bar_time = 0;
double          g_daily_loss = 0;
datetime        g_daily_reset = 0;
int             g_total_orders_today = 0;
datetime        g_position_open_time = 0;  // For max hold time tracking
bool            g_hybrid_sl_moved[1];     // Flag: SL already moved to BE

//+------------------------------------------------------------------+
//| Expert initialization function
//+------------------------------------------------------------------+
int OnInit()
{
    // Validate inputs
    if(!Initialize())
    {
        Print("EA initialization failed");
        return INIT_FAILED;
    }

    // Set magic number for all trades
    m_trade.SetExpertMagicNumber(InpMagicNumber);

    // Set deviation and type filling
    m_trade.SetDeviationInPoints(InpSlippage);
    m_trade.SetTypeFilling(ORDER_FILLING_FOK);

    Print("EA initialized successfully: ", InpExpertName);
    return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    Print("EA deinitialized, reason: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function
//+------------------------------------------------------------------+
void OnTick()
{
    // Check for new bar
    datetime current_bar = iTime(InpSymbol, InpTimeframe, 0);
    if(current_bar == g_last_bar_time)
        return;

    g_last_bar_time = current_bar;

    // Reset daily tracking
    CheckDailyReset();

    // Check kill switches
    if(CheckKillSwitches())
        return;

    // Check trading hours
    if(!IsTradingAllowed())
        return;

    // Main trading logic
    ProcessTradingSignals();
}

//+------------------------------------------------------------------+
//| Initialize EA
//+------------------------------------------------------------------+
bool Initialize()
{
    // Select symbol
    if(!m_symbol.Name(InpSymbol))
    {
        Print("Invalid symbol: ", InpSymbol);
        return false;
    }

    // Check if symbol is selected
    if(!SymbolSelect(InpSymbol, true))
    {
        Print("Failed to select symbol: ", InpSymbol);
        return false;
    }

    return true;
}

//+------------------------------------------------------------------+
//| Check and reset daily tracking
//+------------------------------------------------------------------+
void CheckDailyReset()
{
    datetime today = iTime(InpSymbol, PERIOD_D1, 0);
    if(today != g_daily_reset)
    {
        g_daily_loss = 0;
        g_daily_reset = today;
        g_total_orders_today = 0;
    }
}

//+------------------------------------------------------------------+
//| Check all kill switches
//+------------------------------------------------------------------+
bool CheckKillSwitches()
{
    // Check daily loss cap
    if(InpDailyLossCap > 0)
    {
        double equity = m_account.Equity();
        double balance = m_account.Balance();
        double daily_loss_percent = ((balance - equity) / balance) * 100;

        if(daily_loss_percent >= InpDailyLossCap)
        {
            CloseAllPositions();
            Print("Daily loss cap reached: ", daily_loss_percent, "%");
            return true;
        }
    }

    // Check max orders
    if(g_total_orders_today >= InpMaxOrders)
    {
        Print("Max orders reached today");
        return true;
    }

    return false;
}

//+------------------------------------------------------------------+
//| Check if trading is allowed
//+------------------------------------------------------------------+
bool IsTradingAllowed()
{
    // Check spread
    double spread = m_symbol.Spread();
    if(spread > InpMaxSpread)
    {
        Print("Spread too high: ", spread);
        return false;
    }

    // Check session
    if(!IsInTradingSession())
        return false;

    // Check force close time
    MqlDateTime dt;
    TimeCurrent(dt);
    if(dt.hour >= InpForceCloseHour && InpForceCloseHour > 0)
    {
        // Close existing positions if not holding overnight
        if(!InpOvernightHold)
        {
            CloseAllPositions();
            return false;
        }
    }

    return true;
}

//+------------------------------------------------------------------+
//| Check if in trading session
//+------------------------------------------------------------------+
bool IsInTradingSession()
{
    // Simplified session check
    // In production, implement full session time logic
    MqlDateTime dt;
    TimeCurrent(dt);

    // London session: 08:00 - 16:30
    // US session: 13:00 - 21:00
    // Asia session: 00:00 - 09:00

    if(InpSessionMask == "UK")
    {
        if(dt.hour < 8 || dt.hour >= 16)
            return false;
    }
    else if(InpSessionMask == "US")
    {
        if(dt.hour < 13 || dt.hour >= 21)
            return false;
    }
    else if(InpSessionMask == "Asia")
    {
        if(dt.hour >= 9)
            return false;
    }

    return true;
}

//+------------------------------------------------------------------+
//| Process trading signals
//+------------------------------------------------------------------+
void ProcessTradingSignals()
{
    // Get current positions
    int positions = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        if(PositionGetSymbol(i) == InpSymbol &&
           PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
        {
            positions++;
            ManagePosition(i);
        }
    }

    // Check for entry signals
    if(positions < InpMaxOrders)
    {
        if(CheckEntrySignal())
        {
            OpenPosition();
        }
    }
}

//+------------------------------------------------------------------+
//| Check entry signal
//+------------------------------------------------------------------+
bool CheckEntrySignal()
{
    // Placeholder for actual strategy logic
    // Implement based on {{strategy_type}} strategy

    // Example: Moving average crossover
    double ma1 = iMA(InpSymbol, InpTimeframe, {{ma_fast}}, 0, MODE_SMA, PRICE_CLOSE);
    double ma2 = iMA(InpSymbol, InpTimeframe, {{ma_slow}}, 0, MODE_SMA, PRICE_CLOSE);

    static double last_ma1 = 0;
    static double last_ma2 = 0;

    if(last_ma1 > last_ma2 && ma1 <= ma2)
    {
        // Short signal
        last_ma1 = ma1;
        last_ma2 = ma2;
        return true;
    }
    else if(last_ma1 < last_ma2 && ma1 >= ma2)
    {
        // Long signal
        last_ma1 = ma1;
        last_ma2 = ma2;
        return true;
    }

    last_ma1 = ma1;
    last_ma2 = ma2;

    return false;
}

//+------------------------------------------------------------------+
//| Open new position
//+------------------------------------------------------------------+
void OpenPosition()
{
    double lot_size = CalculateLotSize();
    double price = m_symbol.Bid();
    ENUM_ORDER_TYPE order_type = ORDER_TYPE_SELL;

    // Determine direction
    double ma1 = iMA(InpSymbol, InpTimeframe, {{ma_fast}}, 0, MODE_SMA, PRICE_CLOSE);
    double ma2 = iMA(InpSymbol, InpTimeframe, {{ma_slow}}, 0, MODE_SMA, PRICE_CLOSE);

    if(ma1 > ma2)
    {
        order_type = ORDER_TYPE_BUY;
        price = m_symbol.Ask();
    }

    // Calculate SL/TP distances
    double sl_distance = 0;
    double tp_distance = 0;
    if(InpUseATRStop)
    {
        sl_distance = CalculateATRStopDistance();
    }

    double ask = m_symbol.Ask();
    double bid = m_symbol.Bid();
    double sl = 0;
    double tp = 0;

    if(order_type == ORDER_TYPE_BUY)
    {
        if(sl_distance > 0)
            sl = ask - sl_distance;
        tp = ask + (sl_distance > 0 ? sl_distance * 2 : 0);
    }
    else
    {
        if(sl_distance > 0)
            sl = bid + sl_distance;
        tp = bid - (sl_distance > 0 ? sl_distance * 2 : 0);
    }

    // Reset hybrid SL/TP tracking for new position
    g_position_open_time = TimeCurrent();
    static bool sl_moved_to_be = false;
    static bool partial_executed = false;
    sl_moved_to_be = false;
    partial_executed = false;

    m_trade.Buy(lot_size, InpSymbol, price, sl, tp, InpExpertName);

    if(m_trade.ResultRetcode() != RETCODE_DONE)
    {
        Print("Failed to open position: ", m_trade.ResultRetcodeDescription());
    }
    else
    {
        g_total_orders_today++;
        Print("Position opened: ", order_type == ORDER_TYPE_BUY ? "BUY" : "SELL",
              " Lot: ", lot_size, " Price: ", price);
    }
}

//+------------------------------------------------------------------+
//| Calculate ATR-based stop loss distance
//+------------------------------------------------------------------+
double CalculateATRStopDistance()
{
    if(!InpUseATRStop)
        return 0;

    int handle = iATR(InpSymbol, InpTimeframe, InpATRPeriod);
    if(handle == INVALID_HANDLE)
        return 0;

    double atr[];
    if(CopyBuffer(handle, 0, 0, 1, atr) <= 0)
        return 0;

    return atr[0] * InpATRMultiplier;
}

//+------------------------------------------------------------------+
//| Calculate lot size
//+------------------------------------------------------------------+
double CalculateLotSize()
{
    if(InpFixedLot > 0)
        return MathMin(InpFixedLot, InpMaxLot);

    // Risk-based lot sizing
    double balance = m_account.Balance();
    double risk_amount = balance * (InpRiskPercent / 100.0);

    double tick_value = SymbolInfoDouble(InpSymbol, SYMBOL_TRADE_TICK_VALUE);
    double tick_size = SymbolInfoDouble(InpSymbol, SYMBOL_TRADE_TICK_SIZE);
    double point = SymbolInfoDouble(InpSymbol, SYMBOL_POINT);

    double sl_points = 1000; // Default SL
    if(InpUseATRStop)
    {
        double atr_dist = CalculateATRStopDistance();
        if(atr_dist > 0)
            sl_points = atr_dist / point;
    }
    double lot_size = (risk_amount / (sl_points * tick_value / tick_size)) / (point / tick_size);

    return MathMin(MathMax(lot_size, m_symbol.LotsMin()), InpMaxLot);
}

//+------------------------------------------------------------------+
//| Manage existing position
//+------------------------------------------------------------------+
void ManagePosition(int index)
{
    if(!PositionSelectByTicket(PositionGetTicket(index)))
        return;

    double profit = PositionGetDouble(POSITION_PROFIT);

    // Track position open time on first call
    if(g_position_open_time == 0)
    {
        g_position_open_time = PositionGetInteger(POSITION_TIME);
    }

    // Time-based exit check
    if(InpMaxHoldMinutes > 0)
    {
        MqlDateTime now;
        TimeCurrent(now);
        datetime current_time = StringToTime(TimeToString(TimeCurrent(), TIME_DATE) + " " +
                            IntegerToString(now.hour) + ":" +
                            IntegerToString(now.min) + ":" +
                            IntegerToString(now.sec));

        if(current_time - g_position_open_time >= InpMaxHoldMinutes * 60)
        {
            m_trade.PositionClose(PositionGetTicket(index));
            g_position_open_time = 0;
            return;
        }
    }

    // Use Hybrid SL/TP if enabled
    if(InpUseHybridSLTP)
    {
        ManageHybridSLTP(index);
    }
    else
    {
        // Standard Break even
        if(InpUseBreakEven && profit >= InpBreakEvenTrigger * InpPoint)
        {
            double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
            ENUM_POSITION_TYPE type = PositionGetInteger(POSITION_TYPE);

            double new_sl = (type == POSITION_TYPE_BUY) ?
                open_price + InpBreakEvenDist * InpPoint :
                open_price - InpBreakEvenDist * InpPoint;

            m_trade.PositionModify(PositionGetTicket(index), new_sl, PositionGetDouble(POSITION_SL));
        }

        // Trailing stop
        if(InpUseTrail && profit >= InpTrailDistance * InpPoint)
        {
            double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
            ENUM_POSITION_TYPE type = PositionGetInteger(POSITION_TYPE);

            double new_sl = (type == POSITION_TYPE_BUY) ?
                open_price + InpTrailDistance * InpPoint :
                open_price - InpTrailDistance * InpPoint;

            m_trade.PositionModify(PositionGetTicket(index), new_sl, PositionGetDouble(POSITION_TP));
        }
    }
}

//+------------------------------------------------------------------+
//| Hybrid SL/TP Management
//| Option B+C: BE at 0.5SL, 30% partial at 1SL, RVOL-adaptive TP
//+------------------------------------------------------------------+
void ManageHybridSLTP(int index)
{
    if(!PositionSelectByTicket(PositionGetTicket(index)))
        return;

    double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
    double sl_price = PositionGetDouble(POSITION_SL);
    double tp_price = PositionGetDouble(POSITION_TP);
    double profit = PositionGetDouble(POSITION_PROFIT);
    double volume = PositionGetDouble(POSITION_VOLUME);
    ENUM_POSITION_TYPE type = PositionGetInteger(POSITION_TYPE);
    ulong ticket = PositionGetTicket(index);

    double sl_distance = (type == POSITION_TYPE_BUY) ?
        (open_price - sl_price) / SymbolInfoDouble(InpSymbol, SYMBOL_POINT) :
        (sl_price - open_price) / SymbolInfoDouble(InpSymbol, SYMBOL_POINT);

    double current_profit_pips = (type == POSITION_TYPE_BUY) ?
        (SymbolInfoDouble(InpSymbol, SYMBOL_BID) - open_price) / SymbolInfoDouble(InpSymbol, SYMBOL_POINT) :
        (open_price - SymbolInfoDouble(InpSymbol, SYMBOL_ASK)) / SymbolInfoDouble(InpSymbol, SYMBOL_POINT);

    // Step 1: At InpBETriggerPct (0.5x) SL profit — move SL to breakeven
    double be_trigger_pips = sl_distance * InpBETriggerPct;
    static bool sl_moved_to_be = false;  // Per-position flag (reset per position)

    if(current_profit_pips >= be_trigger_pips && sl_price > 0 && !sl_moved_to_be)
    {
        double new_sl = (type == POSITION_TYPE_BUY) ?
            open_price + InpBreakEvenDist * InpPoint :
            open_price - InpBreakEvenDist * InpPoint;
        m_trade.PositionModify(ticket, new_sl, tp_price);
        sl_moved_to_be = true;
        Print("Hybrid SL/TP: SL moved to breakeven at profit ", current_profit_pips, " pips");
    }

    // Step 2: At 1x SL profit — close InpPartialClosePct (30%) partial
    double partial_trigger_pips = sl_distance * 1.0;
    static bool partial_executed = false;  // Per-position flag

    if(current_profit_pips >= partial_trigger_pips && volume > InpFixedLot * 0.5 && !partial_executed)
    {
        double partial_volume = volume * (InpPartialClosePct / 100.0);
        m_trade.PositionClosePartial(ticket, partial_volume);
        partial_executed = true;
        Print("Hybrid SL/TP: Partial close ", InpPartialClosePct, "% at profit ", current_profit_pips, " pips");
    }

    // Step 3: RVOL-adaptive TP (TP=3R if RVOL>=InpRVOLThreshold, else TP=2R)
    // Note: RVOL reading from SVSS Redis channel in production
    double rvol = 1.0;  // Default; replace with SVSS RVOL reading
    double tp_distance_pips = (rvol >= InpRVOLThreshold) ? sl_distance * 3.0 : sl_distance * 2.0;
    double new_tp = (type == POSITION_TYPE_BUY) ?
        open_price + tp_distance_pips * InpPoint :
        open_price - tp_distance_pips * InpPoint;

    if(rvol >= InpRVOLThreshold && tp_price != new_tp)
    {
        m_trade.PositionModify(ticket, sl_price, new_tp);
        Print("Hybrid SL/TP: RVOL=", rvol, " TP set to 3R at ", tp_distance_pips, " pips");
    }
}

//+------------------------------------------------------------------+
//| Close all positions
//+------------------------------------------------------------------+
void CloseAllPositions()
{
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        if(PositionGetSymbol(i) == InpSymbol &&
           PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
        {
            m_trade.PositionClose(PositionGetTicket(i));
        }
    }
}

//+------------------------------------------------------------------+
//| Get current spread in points
//+------------------------------------------------------------------+
double GetSpreadPoints()
{
    return m_symbol.Spread() / m_symbol.Point();
}

//+------------------------------------------------------------------+
//| Strategy-specific parameters
//+------------------------------------------------------------------+
#property icon "Resources/icon.png"
#property description "{{strategy_description}}"
'''

# Parameter mapping from TRD to MQL5
TRD_TO_MQL5_MAPPING = {
    "session_mask": ("InpSessionMask", "string"),
    "force_close_hour": ("InpForceCloseHour", "int"),
    "overnight_hold": ("InpOvernightHold", "bool"),
    "daily_loss_cap": ("InpDailyLossCap", "double"),
    "spread_filter": ("InpMaxSpread", "double"),
    "max_spread_entry": ("InpMaxSpread", "double"),
    "slippage": ("InpSlippage", "int"),
    "magic_number": ("InpMagicNumber", "int"),
    "max_orders": ("InpMaxOrders", "int"),
    "max_lots": ("InpMaxLot", "double"),
    "fixed_lot_size": ("InpFixedLot", "double"),
    "risk_percent": ("InpRiskPercent", "double"),
    "trailing_stop": ("InpUseTrail", "bool"),
    "trailing_distance": ("InpTrailDistance", "int"),
    "break_even_trigger": ("InpBreakEvenTrigger", "int"),
    "break_even_distance": ("InpBreakEvenDist", "int"),
}


class EABaseTemplate:
    """
    Encapsulates MQL5 EA template rendering and validation.

    Usage:
        template = EABaseTemplate()
        mql5_code = template.render(trd)
        is_valid, errors = template.validate(mql5_source)
    """

    def __init__(self):
        self._defaults = {
            "magic_number": "123456",
            "max_orders": "5",
            "spread_filter": "30",
            "slippage": "3",
            "daily_loss_cap": "5.0",
            "session_mask": "UK/US",
            "force_close_hour": "22",
            "overnight_hold": "false",
            "use_trailing_stop": "false",
            "trailing_distance": "50",
            "use_break_even": "false",
            "break_even_trigger": "100",
            "break_even_distance": "10",
            "ma_fast": "10",
            "ma_slow": "20",
            "bot_type": "scalping",
            "session_tags": "LONDON,NEW_YORK",
            "news_blackout": "true",
        }

    def render(self, trd: "TRDDocument") -> str:
        """
        Render EA_TEMPLATE from TRD document.

        Args:
            trd: TRD document with parameters

        Returns:
            Generated MQL5 source code as string
        """
        if not trd.strategy_id or not trd.strategy_name:
            raise ValueError("TRD must have strategy_id and strategy_name")

        variables = self._prepare_template_variables(trd)
        code = EA_TEMPLATE

        for key, value in variables.items():
            placeholder = "{{" + key + "}}"
            code = code.replace(placeholder, str(value))

        # Remove any remaining placeholders (set to defaults)
        code = re.sub(r'\{\{(\w+)\}\}', '', code)

        return code

    def _prepare_template_variables(self, trd: "TRDDocument") -> Dict[str, Any]:
        """Prepare template variables from TRD document."""
        variables: Dict[str, Any] = {
            "strategy_name": trd.strategy_name.replace(" ", "_"),
            "strategy_id": trd.strategy_id,
            "version": trd.version,
            "generated_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "strategy_type": trd.strategy_type.value if hasattr(trd.strategy_type, 'value') else str(trd.strategy_type) if trd.strategy_type else "trend",
            "strategy_description": trd.description or "Generated by QUANTMINDX",
        }

        variables["symbol"] = trd.symbol
        variables["timeframe"] = trd.timeframe

        # EA template fields
        variables["bot_type"] = trd.bot_type if trd.bot_type else "scalping"
        variables["session_tags"] = ",".join(trd.session_tags) if trd.session_tags else "LONDON,NEW_YORK"
        variables["news_blackout"] = "true" if trd.news_blackout else "false"

        self._map_parameters(trd, variables)

        if trd.position_sizing:
            ps = trd.position_sizing
            variables["fixed_lot_size"] = str(ps.fixed_lot_size)
            variables["max_lots"] = str(ps.max_lots)
            variables["risk_percent"] = str(ps.risk_percent)
        else:
            variables["fixed_lot_size"] = "0.01"
            variables["max_lots"] = "1.0"
            variables["risk_percent"] = "1.0"

        for key, default_value in self._defaults.items():
            if key not in variables:
                variables[key] = default_value

        return variables

    def _map_parameters(self, trd: "TRDDocument", variables: Dict[str, Any]) -> None:
        """Map TRD parameters to template variables."""
        for trd_param, (mql_var, mql_type) in TRD_TO_MQL5_MAPPING.items():
            value = trd.parameters.get(trd_param)

            if value is not None:
                if mql_type == "bool":
                    value = "true" if value else "false"
                elif mql_type == "string":
                    value = str(value)

                variables[mql_var] = value

    def validate(self, mql5_source: str) -> Tuple[bool, List[str]]:
        """
        Validate rendered MQL5 source.

        Args:
            mql5_source: MQL5 source code to validate

        Returns:
            Tuple of (is_valid, list_of_errors)
        """
        errors: List[str] = []

        lines = mql5_source.split('\n')
        brace_count = 0
        paren_count = 0

        for i, line in enumerate(lines, 1):
            brace_count += line.count('{') - line.count('}')
            paren_count += line.count('(') - line.count(')')

            if ';;' in line:
                errors.append(f"Line {i}: Double semicolon")

        if brace_count != 0:
            errors.append(f"Unmatched braces: {brace_count} difference")

        if paren_count != 0:
            errors.append(f"Unmatched parentheses: {paren_count} difference")

        required_functions = ['OnInit', 'OnTick', 'OnDeinit']
        for func in required_functions:
            if func not in mql5_source:
                errors.append(f"Missing required function: {func}")

        return len(errors) == 0, errors
