"""
MQL5 EA Base Template

Template for generating MQL5 Expert Advisor code from TRD documents.
"""

EA_TEMPLATE = '''//+------------------------------------------------------------------+
//| {{strategy_name}}.mq5
//| Generated by QUANTMINDX Development Department
//| Strategy ID: {{strategy_id}}
//| Version: {{version}}
//| Generated: {{generated_date}}
//+------------------------------------------------------------------+
#property copyright "QUANTMINDX"
// @version=5
#property strict

//+------------------------------------------------------------------+
//| Includes
//+------------------------------------------------------------------+
#include <Trade/Trade.mqh>
#include <Trade/SymbolInfo.mqh>
#include <Trade/AccountInfo.mqh>

//+------------------------------------------------------------------+
//| Input Parameters
//+------------------------------------------------------------------+
input group "=== EA Configuration ==="
input string   InpExpertName = "{{strategy_name}}";  // EA Name
input int      InpMagicNumber = {{magic_number}};     // Magic Number
input int      InpMaxOrders = {{max_orders}};        // Max Orders

input group "=== Trading Parameters ==="
input double   InpMaxSpread = {{spread_filter}};      // Max Spread (points)
input int      InpSlippage = {{slippage}};           // Slippage (points)
input double   InpDailyLossCap = {{daily_loss_cap}};  // Daily Loss Cap (%)

input group "=== Session Settings ==="
input string   InpSessionMask = "{{session_mask}}";   // Session Mask (UK/US/Asia)
input int      InpForceCloseHour = {{force_close_hour}};  // Force Close Hour (0-23)
input bool     InpOvernightHold = {{overnight_hold}}; // Hold Overnight

input group "=== Position Management ==="
input double   InpFixedLot = {{fixed_lot_size}};      // Fixed Lot Size
input double   InpMaxLot = {{max_lots}};             // Max Lot Size
input double   InpRiskPercent = {{risk_percent}};     // Risk Percent
input bool     InpUseTrail = {{use_trailing_stop}};  // Use Trailing Stop
input int      InpTrailDistance = {{trailing_distance}}; // Trail Distance (points)
input bool     InpUseBreakEven = {{use_break_even}}; // Use Break Even
input int      InpBreakEvenTrigger = {{break_even_trigger}}; // Break Even Trigger (points)
input int      InpBreakEvenDist = {{break_even_distance}}; // Break Even Distance (points)

//+------------------------------------------------------------------+
//| Global Variables
//+------------------------------------------------------------------+
CTrade          m_trade;
CSymbolInfo     m_symbol;
CAccountInfo    m_account;
datetime        g_last_bar_time = 0;
double          g_daily_loss = 0;
datetime        g_daily_reset = 0;
int             g_total_orders_today = 0;

//+------------------------------------------------------------------+
//| Expert initialization function
//+------------------------------------------------------------------+
int OnInit()
{
    // Validate inputs
    if(!Initialize())
    {
        Print("EA initialization failed");
        return INIT_FAILED;
    }

    // Set magic number for all trades
    m_trade.SetExpertMagicNumber(InpMagicNumber);

    // Set deviation and type filling
    m_trade.SetDeviationInPoints(InpSlippage);
    m_trade.SetTypeFilling(ORDER_FILLING_FOK);

    Print("EA initialized successfully: ", InpExpertName);
    return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    Print("EA deinitialized, reason: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function
//+------------------------------------------------------------------+
void OnTick()
{
    // Check for new bar
    datetime current_bar = iTime(InpSymbol, InpTimeframe, 0);
    if(current_bar == g_last_bar_time)
        return;

    g_last_bar_time = current_bar;

    // Reset daily tracking
    CheckDailyReset();

    // Check kill switches
    if(CheckKillSwitches())
        return;

    // Check trading hours
    if(!IsTradingAllowed())
        return;

    // Main trading logic
    ProcessTradingSignals();
}

//+------------------------------------------------------------------+
//| Initialize EA
//+------------------------------------------------------------------+
bool Initialize()
{
    // Select symbol
    if(!m_symbol.Name(InpSymbol))
    {
        Print("Invalid symbol: ", InpSymbol);
        return false;
    }

    // Check if symbol is selected
    if(!SymbolSelect(InpSymbol, true))
    {
        Print("Failed to select symbol: ", InpSymbol);
        return false;
    }

    return true;
}

//+------------------------------------------------------------------+
//| Check and reset daily tracking
//+------------------------------------------------------------------+
void CheckDailyReset()
{
    datetime today = iTime(InpSymbol, PERIOD_D1, 0);
    if(today != g_daily_reset)
    {
        g_daily_loss = 0;
        g_daily_reset = today;
        g_total_orders_today = 0;
    }
}

//+------------------------------------------------------------------+
//| Check all kill switches
//+------------------------------------------------------------------+
bool CheckKillSwitches()
{
    // Check daily loss cap
    if(InpDailyLossCap > 0)
    {
        double equity = m_account.Equity();
        double balance = m_account.Balance();
        double daily_loss_percent = ((balance - equity) / balance) * 100;

        if(daily_loss_percent >= InpDailyLossCap)
        {
            CloseAllPositions();
            Print("Daily loss cap reached: ", daily_loss_percent, "%");
            return true;
        }
    }

    // Check max orders
    if(g_total_orders_today >= InpMaxOrders)
    {
        Print("Max orders reached today");
        return true;
    }

    return false;
}

//+------------------------------------------------------------------+
//| Check if trading is allowed
//+------------------------------------------------------------------+
bool IsTradingAllowed()
{
    // Check spread
    double spread = m_symbol.Spread();
    if(spread > InpMaxSpread)
    {
        Print("Spread too high: ", spread);
        return false;
    }

    // Check session
    if(!IsInTradingSession())
        return false;

    // Check force close time
    MqlDateTime dt;
    TimeCurrent(dt);
    if(dt.hour >= InpForceCloseHour && InpForceCloseHour > 0)
    {
        // Close existing positions if not holding overnight
        if(!InpOvernightHold)
        {
            CloseAllPositions();
            return false;
        }
    }

    return true;
}

//+------------------------------------------------------------------+
//| Check if in trading session
//+------------------------------------------------------------------+
bool IsInTradingSession()
{
    // Simplified session check
    // In production, implement full session time logic
    MqlDateTime dt;
    TimeCurrent(dt);

    // London session: 08:00 - 16:30
    // US session: 13:00 - 21:00
    // Asia session: 00:00 - 09:00

    if(InpSessionMask == "UK")
    {
        if(dt.hour < 8 || dt.hour >= 16)
            return false;
    }
    else if(InpSessionMask == "US")
    {
        if(dt.hour < 13 || dt.hour >= 21)
            return false;
    }
    else if(InpSessionMask == "Asia")
    {
        if(dt.hour >= 9)
            return false;
    }

    return true;
}

//+------------------------------------------------------------------+
//| Process trading signals
//+------------------------------------------------------------------+
void ProcessTradingSignals()
{
    // Get current positions
    int positions = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        if(PositionGetSymbol(i) == InpSymbol &&
           PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
        {
            positions++;
            ManagePosition(i);
        }
    }

    // Check for entry signals
    if(positions < InpMaxOrders)
    {
        if(CheckEntrySignal())
        {
            OpenPosition();
        }
    }
}

//+------------------------------------------------------------------+
//| Check entry signal
//+------------------------------------------------------------------+
bool CheckEntrySignal()
{
    // Placeholder for actual strategy logic
    // Implement based on {{strategy_type}} strategy

    // Example: Moving average crossover
    double ma1 = iMA(InpSymbol, InpTimeframe, {{ma_fast}}, 0, MODE_SMA, PRICE_CLOSE);
    double ma2 = iMA(InpSymbol, InpTimeframe, {{ma_slow}}, 0, MODE_SMA, PRICE_CLOSE);

    static double last_ma1 = 0;
    static double last_ma2 = 0;

    if(last_ma1 > last_ma2 && ma1 <= ma2)
    {
        // Short signal
        last_ma1 = ma1;
        last_ma2 = ma2;
        return true;
    }
    else if(last_ma1 < last_ma2 && ma1 >= ma2)
    {
        // Long signal
        last_ma1 = ma1;
        last_ma2 = ma2;
        return true;
    }

    last_ma1 = ma1;
    last_ma2 = ma2;

    return false;
}

//+------------------------------------------------------------------+
//| Open new position
//+------------------------------------------------------------------+
void OpenPosition()
{
    double lot_size = CalculateLotSize();
    double price = m_symbol.Bid();
    ENUM_ORDER_TYPE order_type = ORDER_TYPE_SELL;

    // Determine direction
    double ma1 = iMA(InpSymbol, InpTimeframe, {{ma_fast}}, 0, MODE_SMA, PRICE_CLOSE);
    double ma2 = iMA(InpSymbol, InpTimeframe, {{ma_slow}}, 0, MODE_SMA, PRICE_CLOSE);

    if(ma1 > ma2)
    {
        order_type = ORDER_TYPE_BUY;
        price = m_symbol.Ask();
    }

    m_trade.Buy(lot_size, InpSymbol, price, 0, 0, InpExpertName);

    if(m_trade.ResultRetcode() != RETCODE_DONE)
    {
        Print("Failed to open position: ", m_trade.ResultRetcodeDescription());
    }
    else
    {
        g_total_orders_today++;
        Print("Position opened: ", order_type == ORDER_TYPE_BUY ? "BUY" : "SELL",
              " Lot: ", lot_size, " Price: ", price);
    }
}

//+------------------------------------------------------------------+
//| Calculate lot size
//+------------------------------------------------------------------+
double CalculateLotSize()
{
    if(InpFixedLot > 0)
        return MathMin(InpFixedLot, InpMaxLot);

    // Risk-based lot sizing
    double balance = m_account.Balance();
    double risk_amount = balance * (InpRiskPercent / 100.0);

    double tick_value = SymbolInfoDouble(InpSymbol, SYMBOL_TRADE_TICK_VALUE);
    double tick_size = SymbolInfoDouble(InpSymbol, SYMBOL_TRADE_TICK_SIZE);
    double point = SymbolInfoDouble(InpSymbol, SYMBOL_POINT);

    double sl_points = 1000; // Default SL
    double lot_size = (risk_amount / (sl_points * tick_value / tick_size)) / (point / tick_size);

    return MathMin(MathMax(lot_size, m_symbol.LotsMin()), InpMaxLot);
}

//+------------------------------------------------------------------+
//| Manage existing position
//+------------------------------------------------------------------+
void ManagePosition(int index)
{
    if(!PositionSelectByTicket(PositionGetTicket(index)))
        return;

    double profit = PositionGetDouble(POSITION_PROFIT);

    // Break even
    if(InpUseBreakEven && profit >= InpBreakEvenTrigger * InpPoint)
    {
        double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
        ENUM_POSITION_TYPE type = PositionGetInteger(POSITION_TYPE);

        double new_sl = (type == POSITION_TYPE_BUY) ?
            open_price + InpBreakEvenDist * InpPoint :
            open_price - InpBreakEvenDist * InpPoint;

        m_trade.PositionModify(PositionGetTicket(index), new_sl, PositionGetDouble(POSITION_SL));
    }

    // Trailing stop
    if(InpUseTrail && profit >= InpTrailDistance * InpPoint)
    {
        double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
        ENUM_POSITION_TYPE type = PositionGetInteger(POSITION_TYPE);

        double new_sl = (type == POSITION_TYPE_BUY) ?
            open_price + InpTrailDistance * InpPoint :
            open_price - InpTrailDistance * InpPoint;

        m_trade.PositionModify(PositionGetTicket(index), new_sl, PositionGetDouble(POSITION_TP));
    }
}

//+------------------------------------------------------------------+
//| Close all positions
//+------------------------------------------------------------------+
void CloseAllPositions()
{
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        if(PositionGetSymbol(i) == InpSymbol &&
           PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
        {
            m_trade.PositionClose(PositionGetTicket(i));
        }
    }
}

//+------------------------------------------------------------------+
//| Get current spread in points
//+------------------------------------------------------------------+
double GetSpreadPoints()
{
    return m_symbol.Spread() / m_symbol.Point();
}

//+------------------------------------------------------------------+
//| Strategy-specific parameters
//+------------------------------------------------------------------+
#property icon "Resources/icon.png"
#property description "{{strategy_description}}"
'''

# Parameter mapping from TRD to MQL5
TRD_TO_MQL5_MAPPING = {
    "session_mask": ("InpSessionMask", "string"),
    "force_close_hour": ("InpForceCloseHour", "int"),
    "overnight_hold": ("InpOvernightHold", "bool"),
    "daily_loss_cap": ("InpDailyLossCap", "double"),
    "spread_filter": ("InpMaxSpread", "double"),
    "max_spread_entry": ("InpMaxSpread", "double"),
    "slippage": ("InpSlippage", "int"),
    "magic_number": ("InpMagicNumber", "int"),
    "max_orders": ("InpMaxOrders", "int"),
    "max_lots": ("InpMaxLot", "double"),
    "fixed_lot_size": ("InpFixedLot", "double"),
    "risk_percent": ("InpRiskPercent", "double"),
    "trailing_stop": ("InpUseTrail", "bool"),
    "trailing_distance": ("InpTrailDistance", "int"),
    "break_even_trigger": ("InpBreakEvenTrigger", "int"),
    "break_even_distance": ("InpBreakEvenDist", "int"),
}
